import { InfoIcon, VenetianMaskIcon } from "lucide-react";
import { LeaderboardTabs } from "@/components/leaderboard-tabs";
import { repository } from "@/lib/api/repository";
import { buildImposterLeaderboard } from "@/lib/leaderboard/imposter";

export const dynamic = "force-dynamic";

export default async function ImposterLeaderboardPage() {
  const rows = buildImposterLeaderboard(await repository().listReplaysByGame("imposter"));
  return <div className="mx-auto flex w-full max-w-7xl flex-col gap-8 py-10 sm:py-16">
    <header className="flex flex-col gap-4"><LeaderboardTabs active="imposter" /><div className="flex size-11 items-center justify-center rounded-xl border bg-card shadow-sm"><VenetianMaskIcon className="size-5" /></div><div><p className="text-sm font-medium text-muted-foreground">Game leaderboard</p><h1 className="font-heading text-4xl font-semibold tracking-tight sm:text-5xl">Imposter</h1><p className="mt-2 max-w-2xl text-muted-foreground">Social deduction performance across both Crew and Imposter roles.</p></div></header>
    <section className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-heading font-semibold">Model rankings</h2><p className="text-xs text-muted-foreground">Composite score out of 100</p></div><div className="group relative"><button aria-label="How the Imposter score is calculated" className="flex size-9 items-center justify-center rounded-lg border hover:bg-muted" type="button"><InfoIcon className="size-4" /></button><div className="absolute top-11 right-0 z-20 hidden w-80 rounded-xl border bg-popover p-4 text-sm shadow-xl group-hover:block group-focus-within:block" role="tooltip"><p className="font-medium">Imposter Score</p><p className="mt-2 leading-5 text-muted-foreground">55% Bayesian-adjusted win rate + 15% role balance + 10% Crew accusation accuracy + 5% player-deceived rate + 5% valid actions + 5% speed + 5% cost.</p><p className="mt-2 leading-5 text-muted-foreground">Player-deceived rate is the share of Crew accusations cast for someone other than the actual Imposter while this model is the Imposter.</p></div></div></div>
      {rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[82rem] text-sm"><thead className="bg-muted/60 text-left text-xs uppercase tracking-wider text-muted-foreground"><tr>{['Rank','Model','Score','Win rate','Crew win rate','Imposter win rate','Accusation accuracy','Player deceived rate','Time / action','Est. cost / game','Invalid rate'].map((label,i)=><th className={`px-5 py-4 font-medium ${i>1?'text-right':''}`} key={label}>{label}</th>)}</tr></thead><tbody>{rows.map(row=><tr className="border-t hover:bg-muted/30" key={row.modelId}><td className="px-5 py-4 font-mono text-muted-foreground">#{row.rank}</td><td className="px-5 py-4"><div className="font-medium">{row.displayName}</div><div className="text-xs text-muted-foreground">{row.games} games{row.provisional?' · Provisional':''}</div></td><Cell value={row.score.toFixed(1)} strong/><Cell value={pct(row.winRate)}/><Cell value={optionalPct(row.crewWinRate)}/><Cell value={optionalPct(row.imposterWinRate)}/><Cell value={pct(row.accusationAccuracy)}/><Cell value={optionalPct(row.playerDeceivedRate)}/><Cell value={duration(row.avgTimePerActionMs)}/><Cell value={money(row.costPerGame)}/><Cell value={pct(row.invalidActionRate)}/></tr>)}</tbody></table></div>:<div className="px-6 py-16 text-center text-muted-foreground">Complete an Imposter benchmark to populate this leaderboard.</div>}
    </section><p className="text-xs text-muted-foreground">Role balance uses separately adjusted Crew and Imposter performance. Models with fewer than 10 seat games are provisional.</p>
  </div>;
}
function Cell({value,strong=false}:{value:string;strong?:boolean}){return <td className={`px-5 py-4 text-right font-mono ${strong?'font-semibold':''}`}>{value}</td>}
function pct(v:number){return new Intl.NumberFormat('en-US',{style:'percent',maximumFractionDigits:1}).format(v)}
function optionalPct(v:number|null){return v===null?'—':pct(v)}
function duration(ms:number){return ms<1000?`${Math.round(ms)}ms`:`${(ms/1000).toFixed(2)}s`}
function money(v:number|null){return v===null?'—':v<.001?`$${v.toFixed(5)}`:`$${v.toFixed(3)}`}
