// Generates ../src/codenamesWords.ts from codenames_words.txt.
//
// Run this once (and re-run whenever you edit the word list):
//   node generate-words.mjs
//
// It reads codenames_words.txt (one word per line), normalizes the entries
// (trim, uppercase, drop blanks, dedupe), validates they're single alphabetic
// tokens, and writes codenamesWords.ts exporting WORDS.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));

/** Read the word list into a deduped array of uppercase, single-token words. */
function loadWords(fileName) {
  const raw = readFileSync(join(here, fileName), "utf8");
  const words = raw
    .split(/\r?\n/)
    .map((line) => line.trim().toUpperCase())
    .filter((word) => word.length > 0);

  const invalid = words.filter((word) => !/^[A-Z]+$/.test(word));
  if (invalid.length > 0) {
    throw new Error(
      `${fileName}: found ${invalid.length} entr${invalid.length === 1 ? "y" : "ies"} that are not single alphabetic words, ` +
        `e.g. ${JSON.stringify(invalid.slice(0, 5))}`,
    );
  }

  return [...new Set(words)];
}

/** Serialize a word array as a TS literal, wrapped to keep line length sane. */
function toTsArray(words) {
  const perLine = 10;
  const lines = [];
  for (let i = 0; i < words.length; i += perLine) {
    const chunk = words.slice(i, i + perLine).map((w) => `"${w}"`);
    lines.push("  " + chunk.join(", ") + ",");
  }
  return "[\n" + lines.join("\n") + "\n]";
}

const words = loadWords("codenames_words.txt");

if (words.length < 25) {
  throw new Error(`Need at least 25 words to fill a board; got ${words.length}.`);
}

const output = `// AUTO-GENERATED by generate-words.mjs — do not edit by hand.
// Regenerate with:  node scripts/generate-words.mjs

/** The Codenames word pool (${words.length} words). Each game draws 25 at random. */
export const WORDS: readonly string[] = ${toTsArray(words)};
`;

// Write to the codenames/ root (one level up from this scripts/ folder), which
// is where codenames.ts imports it from.
writeFileSync(join(here, "..", "src", "codenamesWords.ts"), output, "utf8");

console.log(`Wrote ../src/codenamesWords.ts — ${words.length} words.`);
