// Generates ../imposterWords.ts from imposter_words.txt.
//
// Run this once (and re-run whenever you edit the word list):
//   node generate-words.mjs
//
// Each source line is "WORD | vague hint". The Crew see WORD exactly; the
// Imposter sees only the hint. This normalizes the entries (uppercase word,
// trimmed hint, drop blanks/comments, validate shape, dedupe on the word) and
// writes imposterWords.ts exporting WORD_HINTS.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));

/** Parse the source file into a deduped array of { word, hint }. */
function loadPairs(fileName) {
  const raw = readFileSync(join(here, fileName), "utf8");
  const pairs = [];
  const seen = new Set();

  raw.split(/\r?\n/).forEach((line, i) => {
    const trimmed = line.trim();
    if (trimmed === "" || trimmed.startsWith("#")) return;

    const sep = trimmed.indexOf("|");
    if (sep === -1) throw new Error(`${fileName}:${i + 1}: expected "WORD | hint", got: ${trimmed}`);

    const word = trimmed.slice(0, sep).trim().toUpperCase();
    const hint = trimmed.slice(sep + 1).trim();
    if (!/^[A-Z]+$/.test(word)) throw new Error(`${fileName}:${i + 1}: word must be a single alphabetic token, got: "${word}"`);
    if (hint === "") throw new Error(`${fileName}:${i + 1}: missing hint for "${word}"`);
    if (seen.has(word)) return; // dedupe on the word
    seen.add(word);
    pairs.push({ word, hint });
  });

  return pairs;
}

/** Serialize as a TS array literal, one pair per line. */
function toTsArray(pairs) {
  const lines = pairs.map((p) => `  { word: ${JSON.stringify(p.word)}, hint: ${JSON.stringify(p.hint)} },`);
  return "[\n" + lines.join("\n") + "\n]";
}

const pairs = loadPairs("imposter_words.txt");
if (pairs.length < 1) throw new Error("Need at least one word/hint pair.");

const output = `// AUTO-GENERATED by generate-words.mjs — do not edit by hand.
// Regenerate with:  node scripts/generate-words.mjs

/** A secret word and the vague hint the Imposter sees instead of it. */
export interface WordHint {
  word: string;
  hint: string;
}

/** The word/hint pool (${pairs.length} pairs). Each game draws one at random. */
export const WORD_HINTS: readonly WordHint[] = ${toTsArray(pairs)};
`;

writeFileSync(join(here, "..", "imposterWords.ts"), output, "utf8");
console.log(`Wrote ../imposterWords.ts — ${pairs.length} word/hint pairs.`);
