// Generates wordleWords.ts from the two source .txt word lists.
//
// Run this once (and re-run whenever you edit the .txt files):
//   node generate-words.mjs
//
// It reads wordle_answers.txt and wordle_allowed_guesses.txt (one 5-letter
// word per line), normalizes them (trim, uppercase, drop blanks, dedupe),
// and writes wordleWords.ts exporting ANSWER_WORDS and ALLOWED_GUESSES.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));

/** Read a word-list file into a deduped array of uppercase 5-letter words. */
function loadWords(fileName) {
  const raw = readFileSync(join(here, fileName), "utf8");
  const words = raw
    .split(/\r?\n/)
    .map((line) => line.trim().toUpperCase())
    .filter((word) => word.length > 0);

  const invalid = words.filter((word) => !/^[A-Z]{5}$/.test(word));
  if (invalid.length > 0) {
    throw new Error(
      `${fileName}: found ${invalid.length} entr${invalid.length === 1 ? "y" : "ies"} that are not 5-letter words, ` +
        `e.g. ${JSON.stringify(invalid.slice(0, 5))}`,
    );
  }

  return [...new Set(words)];
}

/** Serialize a word array as a TS literal, wrapped to keep line length sane. */
function toTsArray(words) {
  const perLine = 10;
  const lines = [];
  for (let i = 0; i < words.length; i += perLine) {
    const chunk = words.slice(i, i + perLine).map((w) => `"${w}"`);
    lines.push("  " + chunk.join(", ") + ",");
  }
  return "[\n" + lines.join("\n") + "\n]";
}

const answers = loadWords("wordle_answers.txt");
const allowed = loadWords("wordle_allowed_guesses.txt");

const output = `// AUTO-GENERATED by generate-words.mjs — do not edit by hand.
// Regenerate with:  node generate-words.mjs

/** The pool of possible secret answers (${answers.length} words). */
export const ANSWER_WORDS: readonly string[] = ${toTsArray(answers)};

/** Additional words accepted as guesses but never chosen as answers (${allowed.length} words). */
export const ALLOWED_GUESSES: readonly string[] = ${toTsArray(allowed)};
`;

writeFileSync(join(here, "..", "src", "wordleWords.ts"), output, "utf8");

console.log(
  `Wrote wordleWords.ts — ${answers.length} answers, ${allowed.length} allowed guesses.`,
);
